spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;AUTO_SERVER=true
    username: sa
    password: "{cipher}AQCiaF4n1N2MOZdGkbtZobgtvqW3zZOXOBvX1HLl143v8DitypfrLM3ttKZykbunvOFtOtBK2ozx1xavsy5XAjmRZuuiCkbl7e9TAOhp6wys1rLgnW3JKRXNBbKz557p23l1xEfZkQSdFCbMnAZ1XaxZYMFCMlbSFDX3nTHAV9EBORy+SpBj8BxTIlW2gELDu601toMjcPcaDbWEtHI3fG1klqi5tG24UR9SWrEXO7eEmMyaUxt/YXg4rn4H9qIRYFk9sYC4+XsWKefkySs3ryTwwyehUJsXHSwwmX2gCNd8NMV+qvKpXPmyAQ3tJEYEdoOHdwL+Q5HdhdbOeJhhljeyUdJH15xe/J3T6SjM1dfwYTDXUeN/9PtT9PmxVWDNSUI=" # POST 127.0.0.1:8888/encrypt로 abc를 보냈을 때 나온 결과 - Asymmetric
token:
  expiration_time: 86400000 # 하루
  secret: "{cipher}AQBkQsOTWRMJTvtEC4h7fTAxepl+K0zkcWhbDzR43Tnbou1n5KH+13PxPKp8j4nTnPHL/Sx98HAY/4vLiXhJzltVELQwalaHnwhhTVYDzYg2rAMDrjENbc+dL937WjpjUBkUsEZp7y2OhNMqNR0ht6oc6nKiK8M14eZjZwodoi2QES6p4ZHROF6+G0nIuzNHQwZHTq8VkIOBgZ7UrQNje/2mOSV0LctG4Iguy3JPiUM6E+NykddI/Xk53HJrPMDEwhIxXY5f/9yFhz+r9BA/2WUsUFuo4cm1fkLKLIS2tcfz2CzvCld7B1FQ/v2dkAWCPWBUf6luiCpxwqK/dIEbmkfQMDpl+Sqc3sWer3jtKqSb8loTqo016cLPOy7iX2BqMetIf4+DjWcTWO8DFqX3XTe4" # POST 127.0.0.1:8888/encrypt로 my_token_native_ecommerce를 보냈을 때 나온 결과 - Asymmetric

gateway:
  ip: 218.147.172.23

order_service:
  url: http://order-service/order-service/%s/orders
