server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  config:
    import:
      - classpath:/bootstrap.yml
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=true
    username: sa
    password: abc
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.valume}}
  client:
    register-with-eureka: true
    fetch-registry: true # Eureka 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지를 설정
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # 서버가 가지고 있는 위치값
greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.example.userservice: DEBUG
    org:
      springframework:
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
#token:
#  expiration_time: 86400000 # 하루
#  secret: user_token