server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///C:\Users\kai01\Desktop\cloud-config
          uri: https://github.com/LeeMinki/cloud-config
#          username: [your username]
#          password: [your password]
